type ProgramacaoTeethalignerFormData = {
  id: number;
  user_id: number;
  product_name: string;
  created_at: string;
  status: string;
  patient_name: string;
  addresses: Address[];
  comments: CommentType[];
  accepted: boolean | null;
  personalizando_o_planejamento: string;
  dentes_a_serem_movimentados: string[];
  movimento_dentario: string;
  relacao_de_caninos: string;
  relacao_de_molares: string;
  sobremordida: string;
  linha_media: string;
  informacoes_adicionais: string;
  escaneamento_do_arco_superior: string[];
  escaneamento_do_arco_inferior: string[];
  escaneamento_do_registro_de_mordida: string[];
  escaneamento_link: string;
  encaminhei_email: boolean;
  logomarca: string;
  mensagem_personalizada_embalagem: string;
  caixa: 'Padrão' | 'Premium';
};
