export default [
  { label: 'Acre', value: 'Acre', abbreviation: 'AC' },
  { label: 'Alagoas', value: 'Alagoas', abbreviation: 'AL' },
  { label: 'Amapá', value: 'Amapá', abbreviation: 'AP' },
  { label: 'Amazonas', value: 'Amazonas', abbreviation: 'AM' },
  { label: 'Bahia', value: 'Bahia', abbreviation: 'BA' },
  { label: 'Ceará', value: 'Ceará', abbreviation: 'CE' },
  { label: 'Distrito Federal', value: 'Distrito Federal', abbreviation: 'DF' },
  { label: 'Espírito Santo', value: 'Espírito Santo', abbreviation: 'ES' },
  { label: 'Goiás', value: 'Goiás', abbreviation: 'GO' },
  { label: 'Maranhão', value: 'Maranhão', abbreviation: 'MA' },
  { label: 'Mato Grosso', value: 'Mato Grosso', abbreviation: 'MT' },
  {
    label: 'Mato Grosso do Sul',
    value: 'Mato Grosso do Sul',
    abbreviation: 'MS',
  },
  { label: 'Minas Gerais', value: 'Minas Gerais', abbreviation: 'MG' },
  { label: 'Pará', value: 'Pará', abbreviation: 'PA' },
  { label: 'Paraíba', value: 'Paraíba', abbreviation: 'PB' },
  { label: 'Paraná', value: 'Paraná', abbreviation: 'PR' },
  { label: 'Pernambuco', value: 'Pernambuco', abbreviation: 'PE' },
  { label: 'Piauí', value: 'Piauí', abbreviation: 'PI' },
  { label: 'Rio de  Janeiro', value: 'Rio de  Janeiro', abbreviation: 'RJ' },
  {
    label: 'Rio Grande do Norte',
    value: 'Rio Grande do Norte',
    abbreviation: 'RN',
  },
  {
    label: 'Rio Grande do Sul',
    value: 'Rio Grande do Sul',
    abbreviation: 'RG',
  },
  { label: 'Rondônia', value: 'Rondônia', abbreviation: 'RO' },
  { label: 'Roraima', value: 'Roraima', abbreviation: 'RR' },
  { label: 'Santa Catarina', value: 'Santa Catarina', abbreviation: 'SC' },
  { label: 'São Paulo', value: 'São Paulo', abbreviation: 'SP' },
  { label: 'Sergipe', value: 'Sergipe', abbreviation: 'SE' },
  { label: 'Tocantins', value: 'Tocantins', abbreviation: 'TO' },
];
